import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/reduxProvider";
import Navbar from "@/components/navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <ToastContainer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
